sudo: required
dist: trusty
services:
  - docker
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update

  # for the tests
  - sudo apt-get install maven

  # for the haskell lms
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get -qq update
  - sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
  - export PATH="$PATH:$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin"

  # for the mono/nancy lms
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  # mono has its own cacerts rather than using the system copy
  - sudo apt-get install mono-complete ca-certificates-mono nuget

script:
  - ./pre-commit.sh
  
cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/.nuget/packages
    - $HOME/.ghc
    - $HOME/.cabal
