sudo: required
dist: trusty
services:
  - docker
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update

  # for the tests
  - sudo apt-get install maven

script:
  - ./pre-commit.sh

cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/.cabal
