sudo: required
dist: trusty
services:
  - docker
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update

  # for the tests
  - sudo apt-get install maven

  # for the haskell lms
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get -qq update
  - sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
  - export PATH="$PATH:$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin"


script:
  - ./pre-commit.sh
  
cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/.nuget/packages
    - $HOME/.ghc
    - $HOME/.cabal
